apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: homelab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          value: "Hello from Homelab K8s!"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: homelab
spec:
  selector:
    app: hello-world
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

